CREATE TABLE Utilisateurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    surname VARCHAR(225) NOT NULL,
    name VARCHAR(225) NOT NULL,
    adress VARCHAR(225) NOT NULL,
    password VARCHAR (225) NOT NULL,
    date_naiss VARCHAR(225) NOT NULL,
    genre VARCHAR(225) NOT NULL
);